import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";

const vazir = localFont({
  src: "../public/fonts/Vazir-Light-FD.ttf",
  display: "swap",
});
export const metadata: Metadata = {
  title: "دریافت داده های گردشگری",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl">
      <body className={vazir.className}>
        {children}
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster
            closeButton
            dir="rtl"
            position="top-center"
            richColors
            className={vazir.className}
            theme="light"
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
